### ISSUE TITLE
There is an error

### ISSUE THREAD

**Issue by Aozaki-Rito** [choutianxius/gym-super-mario-bros#1]
There is no FrameStack in wrappers.py,making the code unwork

**Comment by choutianxius** [comment]
Thank you for pointing out the issue. FrameStack should be directly imported from `gym`. I'll fix this latter.

**Comment by choutianxius** [comment]
Added FrameStack back to wrappers.py. It could have been removed by linting tools, because wrappers.py doesn't use it directly. Feel free to contact me for any other issue.
